plugins {
  id("awesome.androidlib.plugin")
}

dependencies {
    
    implementation(project(":layer_0:module_0_35"))
    implementation(project(":layer_0:module_0_10"))
    implementation(project(":layer_0:module_0_50"))
    implementation(project(":layer_0:module_0_30"))
    implementation(project(":layer_0:module_0_16"))
    implementation(project(":layer_0:module_0_40"))
    implementation(project(":layer_0:module_0_20"))
    implementation(project(":layer_0:module_0_8"))
    implementation(project(":layer_0:module_0_21"))
    implementation(project(":layer_0:module_0_13"))
    implementation(project(":layer_0:module_0_39"))
    implementation(project(":layer_0:module_0_4"))
    implementation(project(":layer_0:module_0_24"))
    implementation(project(":layer_0:module_0_47"))
    implementation(project(":layer_0:module_0_7"))
    implementation(project(":layer_0:module_0_33"))
    implementation(project(":layer_0:module_0_28"))
    implementation(project(":layer_0:module_0_11"))
    implementation(project(":layer_0:module_0_9"))
    implementation(project(":layer_0:module_0_49"))
    implementation(project(":layer_0:module_0_38"))
    implementation(project(":layer_0:module_0_19"))
    implementation(project(":layer_0:module_0_34"))
    implementation(project(":layer_0:module_0_32"))
    implementation(project(":layer_0:module_0_52"))
    implementation(project(":layer_0:module_0_3"))
    implementation(project(":layer_0:module_0_25"))
    implementation(project(":layer_0:module_0_31"))
    implementation(project(":layer_0:module_0_37"))
    implementation(project(":layer_0:module_0_26"))
    implementation(project(":layer_0:module_0_44"))
    implementation(project(":layer_0:module_0_46"))
    implementation(project(":layer_0:module_0_2"))
    implementation(project(":layer_0:module_0_48"))
    implementation(project(":layer_0:module_0_27"))
    implementation(project(":layer_0:module_0_5"))
    implementation(project(":layer_0:module_0_45"))
    implementation(project(":layer_0:module_0_43"))
    implementation(project(":layer_0:module_0_17"))
}
        