plugins {
  id("awesome.androidlib.plugin")
}

dependencies {
    
    implementation(project(":layer_0:module_0_21"))
    implementation(project(":layer_0:module_0_38"))
    implementation(project(":layer_0:module_0_48"))
    implementation(project(":layer_0:module_0_28"))
    implementation(project(":layer_0:module_0_7"))
    implementation(project(":layer_0:module_0_17"))
    implementation(project(":layer_0:module_0_10"))
    implementation(project(":layer_0:module_0_20"))
    implementation(project(":layer_0:module_0_2"))
    implementation(project(":layer_0:module_0_32"))
    implementation(project(":layer_0:module_0_22"))
    implementation(project(":layer_0:module_0_29"))
    implementation(project(":layer_0:module_0_13"))
    implementation(project(":layer_0:module_0_40"))
    implementation(project(":layer_0:module_0_31"))
    implementation(project(":layer_0:module_0_44"))
    implementation(project(":layer_0:module_0_39"))
    implementation(project(":layer_0:module_0_8"))
    implementation(project(":layer_0:module_0_35"))
    implementation(project(":layer_0:module_0_42"))
    implementation(project(":layer_0:module_0_43"))
    implementation(project(":layer_0:module_0_45"))
    implementation(project(":layer_0:module_0_23"))
    implementation(project(":layer_0:module_0_27"))
    implementation(project(":layer_0:module_0_19"))
    implementation(project(":layer_0:module_0_50"))
    implementation(project(":layer_0:module_0_33"))
    implementation(project(":layer_0:module_0_34"))
    implementation(project(":layer_0:module_0_46"))
    implementation(project(":layer_0:module_0_52"))
    implementation(project(":layer_0:module_0_11"))
    implementation(project(":layer_0:module_0_9"))
    implementation(project(":layer_0:module_0_24"))
    implementation(project(":layer_0:module_0_36"))
    implementation(project(":layer_0:module_0_41"))
}
        