plugins {
  id("awesome.androidlib.plugin")
}

dependencies {
    
    implementation(project(":layer_0:module_0_38"))
    implementation(project(":layer_0:module_0_45"))
    implementation(project(":layer_0:module_0_18"))
    implementation(project(":layer_0:module_0_32"))
    implementation(project(":layer_0:module_0_10"))
    implementation(project(":layer_0:module_0_4"))
    implementation(project(":layer_0:module_0_1"))
    implementation(project(":layer_0:module_0_43"))
    implementation(project(":layer_0:module_0_19"))
    implementation(project(":layer_0:module_0_51"))
    implementation(project(":layer_0:module_0_26"))
    implementation(project(":layer_0:module_0_42"))
    implementation(project(":layer_0:module_0_36"))
    implementation(project(":layer_0:module_0_33"))
    implementation(project(":layer_0:module_0_8"))
    implementation(project(":layer_0:module_0_47"))
    implementation(project(":layer_0:module_0_37"))
    implementation(project(":layer_0:module_0_31"))
    implementation(project(":layer_0:module_0_40"))
    implementation(project(":layer_0:module_0_52"))
    implementation(project(":layer_0:module_0_29"))
    implementation(project(":layer_0:module_0_46"))
    implementation(project(":layer_0:module_0_16"))
    implementation(project(":layer_0:module_0_7"))
    implementation(project(":layer_0:module_0_15"))
    implementation(project(":layer_0:module_0_12"))
    implementation(project(":layer_0:module_0_34"))
    implementation(project(":layer_0:module_0_30"))
    implementation(project(":layer_0:module_0_48"))
    implementation(project(":layer_0:module_0_11"))
    implementation(project(":layer_0:module_0_28"))
    implementation(project(":layer_0:module_0_17"))
    implementation(project(":layer_0:module_0_39"))
    implementation(project(":layer_0:module_0_6"))
}
        