plugins {
  id("awesome.androidapp.plugin")
}

dependencies {
    
    implementation(project(":layer_4:module_4_108"))
    implementation(project(":layer_4:module_4_109"))
    implementation(project(":layer_4:module_4_110"))
    implementation(project(":layer_4:module_4_111"))
    implementation(project(":layer_4:module_4_112"))
    implementation(project(":layer_4:module_4_113"))
    implementation(project(":layer_4:module_4_114"))
    implementation(project(":layer_4:module_4_115"))
    implementation(project(":layer_4:module_4_116"))
    implementation(project(":layer_4:module_4_117"))
    implementation(project(":layer_4:module_4_118"))
    implementation(project(":layer_4:module_4_119"))
    implementation(project(":layer_4:module_4_120"))
    implementation(project(":layer_4:module_4_121"))
    implementation(project(":layer_4:module_4_122"))
    implementation(project(":layer_4:module_4_123"))
    implementation(project(":layer_4:module_4_124"))
    implementation(project(":layer_4:module_4_125"))
    implementation(project(":layer_4:module_4_126"))
    implementation(project(":layer_4:module_4_127"))
    implementation(project(":layer_4:module_4_128"))
    implementation(project(":layer_4:module_4_129"))
    implementation(project(":layer_4:module_4_130"))
    implementation(project(":layer_4:module_4_131"))
    implementation(project(":layer_4:module_4_132"))
    implementation(project(":layer_4:module_4_133"))
    implementation(project(":layer_4:module_4_134"))
    implementation(project(":layer_4:module_4_135"))
    implementation(project(":layer_4:module_4_136"))
    implementation(project(":layer_4:module_4_137"))
    implementation(project(":layer_4:module_4_138"))
    implementation(project(":layer_4:module_4_139"))
    implementation(project(":layer_4:module_4_140"))
    implementation(project(":layer_4:module_4_141"))
    implementation(project(":layer_4:module_4_142"))
    implementation(project(":layer_4:module_4_143"))
    implementation(project(":layer_4:module_4_144"))
    implementation(project(":layer_4:module_4_145"))
    implementation(project(":layer_4:module_4_146"))
    implementation(project(":layer_4:module_4_147"))
    implementation(project(":layer_4:module_4_148"))
    implementation(project(":layer_4:module_4_149"))
    implementation(project(":layer_4:module_4_150"))
    implementation(project(":layer_4:module_4_151"))
    implementation(project(":layer_4:module_4_152"))
}
        