plugins {
  id("awesome.androidlib.plugin")
}

dependencies {
    
    implementation(project(":layer_0:module_0_18"))
    implementation(project(":layer_0:module_0_13"))
    implementation(project(":layer_0:module_0_19"))
    implementation(project(":layer_0:module_0_36"))
    implementation(project(":layer_0:module_0_32"))
    implementation(project(":layer_0:module_0_47"))
    implementation(project(":layer_0:module_0_44"))
    implementation(project(":layer_0:module_0_27"))
    implementation(project(":layer_0:module_0_49"))
    implementation(project(":layer_0:module_0_42"))
    implementation(project(":layer_0:module_0_9"))
    implementation(project(":layer_0:module_0_14"))
    implementation(project(":layer_0:module_0_12"))
    implementation(project(":layer_0:module_0_28"))
    implementation(project(":layer_0:module_0_40"))
    implementation(project(":layer_0:module_0_30"))
    implementation(project(":layer_0:module_0_8"))
    implementation(project(":layer_0:module_0_6"))
    implementation(project(":layer_0:module_0_5"))
    implementation(project(":layer_0:module_0_33"))
    implementation(project(":layer_0:module_0_35"))
    implementation(project(":layer_0:module_0_39"))
    implementation(project(":layer_0:module_0_2"))
    implementation(project(":layer_0:module_0_17"))
    implementation(project(":layer_0:module_0_7"))
    implementation(project(":layer_0:module_0_26"))
    implementation(project(":layer_0:module_0_10"))
    implementation(project(":layer_0:module_0_23"))
    implementation(project(":layer_0:module_0_16"))
    implementation(project(":layer_0:module_0_15"))
    implementation(project(":layer_0:module_0_50"))
    implementation(project(":layer_0:module_0_37"))
}
        