on:
  push:
    branches: [ main]
jobs:
  iterations:
    name: Generate versions
    runs-on: ubuntu-latest
    steps:
       - id: calculate_iterations
         run: |
          iterations=" ["
          for i in {1..80}
          do
            if [ $i == 1 ]
            then
                iterations="$iterations \"$i\""
            else
              iterations="$iterations  , \"$i\""
            fi
          done
          iterations="$iterations ]"
          echo "iterations=$iterations" >> $GITHUB_OUTPUT
          echo $GITHUB_OUTPUT
    outputs:
       iterations: ${{ steps.calculate_iterations.outputs.iterations }}
  my-job:
    needs: [iterations]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runs:   ${{ fromJson(needs.iterations.outputs.iterations) }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: actions/setup-java@v3
      with:
        distribution: oracle
        java-version: 17

    - name: Use the secret
      run: |

        echo "$MY_JSON_SECRET" > key.json
        ./gradlew lintDebug
        ./gradlew clean compileDebugKotlin
        bash replacer
        ./gradlew lintDebug
        bash replacer
        ./gradlew lintDebug
        bash replacer
        ./gradlew lintDebug
        bash replacer
        ./gradlew lintDebug
        bash replacer
        ./gradlew lintDebug
        bash replacer
        ./gradlew lintDebug
        bash replacer
        ./gradlew lintDebug
        bash replacer
        ./gradlew lintDebug
        bash replacer
        ./gradlew lintDebug
        bash replacer
        ./gradlew lintDebug
        bash replacer
        ./gradlew lintDebug
        bash replacer
        ./gradlew lintDebug
        bash replacer
        ./gradlew lintDebug
        bash replacer
        ./gradlew lintDebug
        bash replacer
        ./gradlew lintDebug
        bash replacer
        ./gradlew lintDebug
      env:
        MY_JSON_SECRET: ${{ secrets.KEY }}
        GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_API_KEY }}
