on:
  push:
    branches: [ main]
jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - uses: actions/setup-java@v3
      with:
        distribution: oracle
        java-version: 17

    - name: Use the secret
      run: |

        echo "$KEY" > key.json
        ./gradlew compileDebugKotlin
        
      env:
        MY_JSON_SECRET: ${{ secrets.KEY }}